export const ACTION_TYPES = {
    SetRepeat: 'SetRepeat',
    SetFrequency: 'SetFrequency',
    SetMonthOption: 'SetMonthOption',
    SetSelectedWeeks: 'SetSelectedWeeks',
    SetMonthDate: 'SetMonthDate',
    SetMonthDay: 'SetMonthDay',
    SetMonthDayOrder: 'SetMonthDayOrder',
    SetInitialProps: 'SetInitialProps',
    SetEndType: 'SetEndType',
    SetEndDate: 'SetEndDate',
    SetEndCount: 'SetEndCount',
    SetStartDate: 'SetStartDate',
    SetCronExp: 'SetCronExp',
}